<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="9" ignored="0" total="10" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="81240" started-at="2021-10-26T17:19:00 GMT" finished-at="2021-10-26T17:20:21 GMT">
    <groups>
    </groups>
    <test name="Test2" duration-ms="38993" started-at="2021-10-26T17:19:00 GMT" finished-at="2021-10-26T17:19:39 GMT">
      <class name="com.gSTAX.Tests.Tricentis">
        <test-method status="PASS" signature="setupDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@47c62251]" name="setupDriver" is-config="true" duration-ms="17431" started-at="2021-10-26T17:19:00 GMT" finished-at="2021-10-26T17:19:18 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupDriver -->
        <test-method status="FAIL" signature="WebsiteTest1()[pri:0, instance:com.gSTAX.Tests.Tricentis@47c62251]" name="WebsiteTest1" duration-ms="17920" started-at="2021-10-26T17:19:18 GMT" finished-at="2021-10-26T17:19:35 GMT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.gSTAX.Tests.Tricentis.WebsiteTest1(Tricentis.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WebsiteTest1 -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@47c62251]" name="quitDriver" is-config="true" duration-ms="3585" started-at="2021-10-26T17:19:36 GMT" finished-at="2021-10-26T17:19:39 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- com.gSTAX.Tests.Tricentis -->
    </test> <!-- Test2 -->
    <test name="Test5" duration-ms="38967" started-at="2021-10-26T17:19:00 GMT" finished-at="2021-10-26T17:19:39 GMT">
      <class name="com.gSTAX.Tests.Tricentis">
        <test-method status="PASS" signature="setupDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@5622fdf]" name="setupDriver" is-config="true" duration-ms="14633" started-at="2021-10-26T17:19:00 GMT" finished-at="2021-10-26T17:19:15 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupDriver -->
        <test-method status="FAIL" signature="WebsiteTest1()[pri:0, instance:com.gSTAX.Tests.Tricentis@5622fdf]" name="WebsiteTest1" duration-ms="21042" started-at="2021-10-26T17:19:15 GMT" finished-at="2021-10-26T17:19:36 GMT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.gSTAX.Tests.Tricentis.WebsiteTest1(Tricentis.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WebsiteTest1 -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@5622fdf]" name="quitDriver" is-config="true" duration-ms="3076" started-at="2021-10-26T17:19:36 GMT" finished-at="2021-10-26T17:19:39 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- com.gSTAX.Tests.Tricentis -->
    </test> <!-- Test5 -->
    <test name="Test3" duration-ms="39307" started-at="2021-10-26T17:19:00 GMT" finished-at="2021-10-26T17:19:39 GMT">
      <class name="com.gSTAX.Tests.Tricentis">
        <test-method status="PASS" signature="setupDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@3bfdc050]" name="setupDriver" is-config="true" duration-ms="17655" started-at="2021-10-26T17:19:00 GMT" finished-at="2021-10-26T17:19:18 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupDriver -->
        <test-method status="FAIL" signature="WebsiteTest1()[pri:0, instance:com.gSTAX.Tests.Tricentis@3bfdc050]" name="WebsiteTest1" duration-ms="17733" started-at="2021-10-26T17:19:18 GMT" finished-at="2021-10-26T17:19:36 GMT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.gSTAX.Tests.Tricentis.WebsiteTest1(Tricentis.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WebsiteTest1 -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@3bfdc050]" name="quitDriver" is-config="true" duration-ms="3913" started-at="2021-10-26T17:19:36 GMT" finished-at="2021-10-26T17:19:39 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- com.gSTAX.Tests.Tricentis -->
    </test> <!-- Test3 -->
    <test name="Test4" duration-ms="42545" started-at="2021-10-26T17:19:00 GMT" finished-at="2021-10-26T17:19:43 GMT">
      <class name="com.gSTAX.Tests.Tricentis">
        <test-method status="PASS" signature="setupDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@6a4f787b]" name="setupDriver" is-config="true" duration-ms="16016" started-at="2021-10-26T17:19:00 GMT" finished-at="2021-10-26T17:19:16 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupDriver -->
        <test-method status="FAIL" signature="WebsiteTest1()[pri:0, instance:com.gSTAX.Tests.Tricentis@6a4f787b]" name="WebsiteTest1" duration-ms="22491" started-at="2021-10-26T17:19:16 GMT" finished-at="2021-10-26T17:19:39 GMT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.gSTAX.Tests.Tricentis.WebsiteTest1(Tricentis.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WebsiteTest1 -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@6a4f787b]" name="quitDriver" is-config="true" duration-ms="4035" started-at="2021-10-26T17:19:39 GMT" finished-at="2021-10-26T17:19:43 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- com.gSTAX.Tests.Tricentis -->
    </test> <!-- Test4 -->
    <test name="Test1" duration-ms="45990" started-at="2021-10-26T17:19:00 GMT" finished-at="2021-10-26T17:19:46 GMT">
      <class name="com.gSTAX.Tests.Tricentis">
        <test-method status="PASS" signature="setupDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@4cc0edeb]" name="setupDriver" is-config="true" duration-ms="17015" started-at="2021-10-26T17:19:00 GMT" finished-at="2021-10-26T17:19:17 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupDriver -->
        <test-method status="FAIL" signature="WebsiteTest1()[pri:0, instance:com.gSTAX.Tests.Tricentis@4cc0edeb]" name="WebsiteTest1" duration-ms="25973" started-at="2021-10-26T17:19:17 GMT" finished-at="2021-10-26T17:19:43 GMT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.gSTAX.Tests.Tricentis.WebsiteTest1(Tricentis.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WebsiteTest1 -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@4cc0edeb]" name="quitDriver" is-config="true" duration-ms="2982" started-at="2021-10-26T17:19:43 GMT" finished-at="2021-10-26T17:19:46 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- com.gSTAX.Tests.Tricentis -->
    </test> <!-- Test1 -->
    <test name="Test7" duration-ms="34654" started-at="2021-10-26T17:19:39 GMT" finished-at="2021-10-26T17:20:14 GMT">
      <class name="com.gSTAX.Tests.Tricentis">
        <test-method status="PASS" signature="setupDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@4667ae56]" name="setupDriver" is-config="true" duration-ms="12853" started-at="2021-10-26T17:19:39 GMT" finished-at="2021-10-26T17:19:52 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupDriver -->
        <test-method status="FAIL" signature="WebsiteTest1()[pri:0, instance:com.gSTAX.Tests.Tricentis@4667ae56]" name="WebsiteTest1" duration-ms="18191" started-at="2021-10-26T17:19:52 GMT" finished-at="2021-10-26T17:20:10 GMT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.gSTAX.Tests.Tricentis.WebsiteTest1(Tricentis.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WebsiteTest1 -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@4667ae56]" name="quitDriver" is-config="true" duration-ms="3599" started-at="2021-10-26T17:20:10 GMT" finished-at="2021-10-26T17:20:14 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- com.gSTAX.Tests.Tricentis -->
    </test> <!-- Test7 -->
    <test name="Test8" duration-ms="34649" started-at="2021-10-26T17:19:40 GMT" finished-at="2021-10-26T17:20:14 GMT">
      <class name="com.gSTAX.Tests.Tricentis">
        <test-method status="PASS" signature="setupDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@6eebc39e]" name="setupDriver" is-config="true" duration-ms="12877" started-at="2021-10-26T17:19:40 GMT" finished-at="2021-10-26T17:19:53 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupDriver -->
        <test-method status="FAIL" signature="WebsiteTest1()[pri:0, instance:com.gSTAX.Tests.Tricentis@6eebc39e]" name="WebsiteTest1" duration-ms="17634" started-at="2021-10-26T17:19:53 GMT" finished-at="2021-10-26T17:20:10 GMT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.gSTAX.Tests.Tricentis.WebsiteTest1(Tricentis.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WebsiteTest1 -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@6eebc39e]" name="quitDriver" is-config="true" duration-ms="4131" started-at="2021-10-26T17:20:10 GMT" finished-at="2021-10-26T17:20:14 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- com.gSTAX.Tests.Tricentis -->
    </test> <!-- Test8 -->
    <test name="Test6" duration-ms="35756" started-at="2021-10-26T17:19:39 GMT" finished-at="2021-10-26T17:20:15 GMT">
      <class name="com.gSTAX.Tests.Tricentis">
        <test-method status="PASS" signature="setupDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@57baeedf]" name="setupDriver" is-config="true" duration-ms="12650" started-at="2021-10-26T17:19:39 GMT" finished-at="2021-10-26T17:19:52 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupDriver -->
        <test-method status="FAIL" signature="WebsiteTest1()[pri:0, instance:com.gSTAX.Tests.Tricentis@57baeedf]" name="WebsiteTest1" duration-ms="18706" started-at="2021-10-26T17:19:52 GMT" finished-at="2021-10-26T17:20:11 GMT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.gSTAX.Tests.Tricentis.WebsiteTest1(Tricentis.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WebsiteTest1 -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@57baeedf]" name="quitDriver" is-config="true" duration-ms="4398" started-at="2021-10-26T17:20:11 GMT" finished-at="2021-10-26T17:20:15 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- com.gSTAX.Tests.Tricentis -->
    </test> <!-- Test6 -->
    <test name="Test9" duration-ms="34780" started-at="2021-10-26T17:19:43 GMT" finished-at="2021-10-26T17:20:18 GMT">
      <class name="com.gSTAX.Tests.Tricentis">
        <test-method status="PASS" signature="setupDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@57fffcd7]" name="setupDriver" is-config="true" duration-ms="11971" started-at="2021-10-26T17:19:43 GMT" finished-at="2021-10-26T17:19:55 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupDriver -->
        <test-method status="FAIL" signature="WebsiteTest1()[pri:0, instance:com.gSTAX.Tests.Tricentis@57fffcd7]" name="WebsiteTest1" duration-ms="20376" started-at="2021-10-26T17:19:55 GMT" finished-at="2021-10-26T17:20:15 GMT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.gSTAX.Tests.Tricentis.WebsiteTest1(Tricentis.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WebsiteTest1 -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@57fffcd7]" name="quitDriver" is-config="true" duration-ms="2431" started-at="2021-10-26T17:20:15 GMT" finished-at="2021-10-26T17:20:18 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- com.gSTAX.Tests.Tricentis -->
    </test> <!-- Test9 -->
    <test name="Test10" duration-ms="35156" started-at="2021-10-26T17:19:46 GMT" finished-at="2021-10-26T17:20:21 GMT">
      <class name="com.gSTAX.Tests.Tricentis">
        <test-method status="PASS" signature="setupDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@553f17c]" name="setupDriver" is-config="true" duration-ms="11797" started-at="2021-10-26T17:19:46 GMT" finished-at="2021-10-26T17:19:58 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupDriver -->
        <test-method status="PASS" signature="WebsiteTest1()[pri:0, instance:com.gSTAX.Tests.Tricentis@553f17c]" name="WebsiteTest1" duration-ms="21931" started-at="2021-10-26T17:19:58 GMT" finished-at="2021-10-26T17:20:20 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WebsiteTest1 -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.gSTAX.Tests.Tricentis@553f17c]" name="quitDriver" is-config="true" duration-ms="1416" started-at="2021-10-26T17:20:20 GMT" finished-at="2021-10-26T17:20:21 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- com.gSTAX.Tests.Tricentis -->
    </test> <!-- Test10 -->
  </suite> <!-- Suite -->
</testng-results>
